version: "2"

run:
  timeout: 5m
  tests: true
  relative-path-mode: gomod
  allow-serial-runners: true

output:
  formats:
    text:
      print-linter-name: true
      print-issued-lines: true
      colors: true
  show-stats: true

linters:
  default: none
  enable:
    - errcheck
    - asciicheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - misspell
    - unconvert
    - unparam
    - gosec
    - prealloc
    - bodyclose
    - nilerr
    - gocyclo
    - dupl
    - goconst
    - gocritic
  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
    gosec:
      excludes:
        - G304
    revive:
      rules:
        - name: package-comments
          disabled: true

formatters:
  enable:
    - gofmt
    - golines

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: true
