version: 2

builds:
  - main: .
    binary: dify
    ldflags:
      - -s -w
      - -X dify-cli/cmd.version={{.Version}}
      - -X dify-cli/cmd.commit={{.Commit}}
      - -X dify-cli/cmd.date={{.Date}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: binary
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

release:
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\(.+\))?!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\(.+\))?!?:.+$'
      order: 1
    - title: Others
      order: 999
