version: 2

builds:
  - main: .
    binary: dify
    ldflags:
      - -s -w
      - -X dify-cli/cmd.version={{.Version}}
      - -X dify-cli/cmd.commit={{.Commit}}
      - -X dify-cli/cmd.date={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\(.+\))?!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\(.+\))?!?:.+$'
      order: 1
    - title: Others
      order: 999
